### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Felonic** [umer0586/winKeyboard#1]
Hey,

The  keyboard.winKeyPress(ScanCode.DIK_UP); does nothing but when 
 keyboard.winKeyRelease(ScanCode.DIK_UP);
 is called, it shows it twice on the console but when trying in game it doesnt do the movements in game, even though its printing on the console that it was pressed?

**Comment by UmerCodez** [comment]
@doomz1 
Try adding `sleep()` between `winKeyPress()` and `winKeyRelease()` i-e
<pre>
keyboard.winKeyPress(ScanCode.DIK_UP);
//Thread.sleep(100);
keyboard.winKeyRelease(ScanCode.DIK_UP);
</pre>

Game should be reading `ScanCode` not `VirtualKeyCode`. These methods are only meant for games that read keyboard scan code. Like some racing games on a **Windows** uses `ScanCode` for arrow keys only. 

On which game you have tried this ?

**Comment by Felonic** [comment]
@umer0586 Thanks for swift response!

Here is the code:
```
Keyboard keyboard = new Keyboard();
keyboard.winKeyPress(ScanCode.DIK_UP);

try {
	Thread.sleep(1000);
} catch (InterruptedException e) {
	e.printStackTrace();
}
keyboard.winKeyRelease(ScanCode.DIK_UP);
```

Here is the output:

```
Key: caps lock
Key: up
Key: up
```

Caps Lock is the key I used to execute the code. When caps lock is pressed, it pauses for 1 second and then instantly shows "Key: up" twice.

This test was conducted on the 32 bit one as 64 bit gives this error:
`java.lang.UnsatisfiedLinkError: E:\Projects\WinKeyboard\SCGen64.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform`

This error prints out when I use this jre:
`C:\Program Files (x86)\Java\jre1.8.0_161\bin\java.exe`

It only works for 32 bit when I use:
`C:\Program Files\Java\jre1.8.0_161\bin\java.exe`

I have both specified jre's though, so not sure why it says that as I even compiled and ran them with the same jre's for each.

I'm testing this on Grand Theft Auto San Andreas

**Comment by UmerCodez** [comment]
@doomz1 
The code you provided is insufficient for me to find out whats going on. How you are detecting **capslock** key and where is the code for printing in console ?

For `java.lang.UnsatisfiedLinkError` i will check and try to fix it soon

Are you sure GTA San Andreas reads keyboard **scan codes** not **virtual keycodes** ?  Game that reads **virtual keycodes** might ignore **scan codes** 

First try sending **virtual keycodes** using `java.awt.Robot` if `java.awt.Robot` doesnt work for a game then go for scancodes (i-e `keyboard.winKeyPress(ScanCode.DIK_UP)` )

**Comment by Felonic** [comment]
@umer0586 
I'm using JNativeHook for the listeners:

```
@Override
public void nativeKeyReleased(NativeKeyEvent nativeEvent) {
    String keyText = NativeKeyEvent.getKeyText(nativeEvent.getKeyCode());
    keyText = keyText.toLowerCase();
    System.out.println("Key: " +keyText);
}
```
      
I did try the Robot Class, it does not register the arrow keys either in-game. I've also tried JNI:
```
	public static void pressKey(int c) {
		INPUT input = new INPUT();
		input.type = new DWORD(INPUT.INPUT_KEYBOARD);
		input.input.setType("ki");
		input.input.ki.wScan = new WORD(0);
		input.input.ki.time = new DWORD(0);
		input.input.ki.dwExtraInfo = new ULONG_PTR(0);
		input.input.ki.wVk = new WORD(c);
		input.input.ki.dwFlags = new DWORD(KEYEVENTF_KEYDOWN);
		User32.INSTANCE.SendInput(new DWORD(1), (INPUT[]) input.toArray(1), input.size());
		input.input.ki.wVk = new WORD(c);
		input.input.ki.dwFlags = new DWORD(KEYEVENTF_KEYUP);
		User32.INSTANCE.SendInput(new DWORD(1), (INPUT[]) input.toArray(1), input.size());
	}    
```
It all registers the key on desktop but in-game there is no movement. I have read DirectX games takes direct input, so my search finally got me here. So far all inputs from these methods register on desktop properly but no movement in the game itself, so I'm not really sure what its using but the game is DirectX .

**Comment by UmerCodez** [comment]
@doomz1 
Hmm, i installed GTA San Andreas and try these methods and found that neither **Virtual Keycode** nor **scancodes** for **arrow key** worked. But the good news is that simulating keys other than arrow keys just worked fine in case of GTA. As in GTA character/vehicle  can also be controlled by **W S A D** keys. I tried simulating these key (W S A D) and it **worked** (for both virtualkeys and scancoode). Just make sure that you are running your IDE as administrator

**Comment by Felonic** [comment]
@umer0586 Oh I see, wonder what they use for arrows. Thanks for your time and efforts umer!

**Comment by UmerCodez** [comment]
> This test was conducted on the 32 bit one as 64 bit gives this error:
java.lang.UnsatisfiedLinkError: E:\Projects\WinKeyboard\SCGen64.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform

@Felonic 
Error has been resolved. 74cbb92a2c9752e5fe249e30971118aa76219977
